version: '3.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    hostname: elastic101
    container_name: cont-elasticsearch
    ports:
      - 9200:9200
    mem_limit: 1g
    networks:
      - elastic
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch-data
        target: /usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.0
    hostname: kibana101
    container_name: cont-kibana
    ports:
      - 5601:5601
    mem_limit: 1g
    networks:
      - elastic
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: filebeat/
    hostname: filebeat101
    container_name: con-filebeat
    networks:
      - elastic
    volumes:
      - type: bind
        source: ./logging-demo/logs
        target: /usr/share/filebeat/logs
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
    driver: local

networks:
  elastic:
    driver: bridge